// build-icons.js — writes src/shared/icons.js from lucide-static (ISC
// licence, https://lucide.dev). Only the curated set below ships, so slides
// render offline and identically every time. Re-run after changing the list:
//   node scripts/build-icons.js
'use strict';

const fs = require('fs');
const path = require('path');

// name in the app → Lucide icon, with the label shown in the icon picker.
const ICONS = [
  ['check', 'check', 'Tick'],
  ['face', 'scan-face', 'Face'],
  ['smile', 'smile', 'Smile'],
  ['user', 'user', 'Person'],
  ['sparkles', 'sparkles', 'Sparkles'],
  ['sparkle', 'sparkle', 'Sparkle'],
  ['droplet', 'droplet', 'Droplet'],
  ['droplets', 'droplets', 'Droplets'],
  ['waves', 'waves', 'Waves'],
  ['syringe', 'syringe', 'Syringe'],
  ['pipette', 'pipette', 'Pipette'],
  ['layers', 'layers', 'Layers'],
  ['spline', 'spline', 'Curve'],
  ['lift', 'move-up-right', 'Lift'],
  ['trend', 'trending-up', 'Improving'],
  ['activity', 'activity', 'Activity'],
  ['zap', 'zap', 'Energy'],
  ['sun', 'sun', 'Sun'],
  ['moon', 'moon', 'Moon'],
  ['shield', 'shield-check', 'Safety'],
  ['stethoscope', 'stethoscope', 'Medical'],
  ['search', 'search', 'Assess'],
  ['hand', 'hand', 'Hand'],
  ['heart', 'heart', 'Heart'],
  ['leaf', 'leaf', 'Leaf'],
  ['flower', 'flower-2', 'Flower'],
  ['gem', 'gem', 'Gem'],
  ['feather', 'feather', 'Feather'],
  ['clock', 'clock', 'Time'],
  ['calendar', 'calendar', 'Calendar'],
  ['target', 'target', 'Target'],
  ['ruler', 'ruler', 'Measure'],
  ['scale', 'scale', 'Balance'],
  ['map-pin', 'map-pin', 'Location'],
  ['message', 'message-circle', 'Message'],
  ['phone', 'phone', 'Phone'],
];

const dir = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const out = {};
for (const [name, lucide, label] of ICONS) {
  const svg = fs.readFileSync(path.join(dir, `${lucide}.svg`), 'utf8');
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'))
    .replace(/\s*\n\s*/g, '').trim();
  out[name] = { label, svg: inner };
}

const body = `// icons.js — GENERATED by scripts/build-icons.js, do not edit by hand.
// Line icons from Lucide (https://lucide.dev), ISC licence:
// Copyright (c) Lucide Icons and Contributors. Permission to use, copy,
// modify, and/or distribute this software for any purpose with or without fee
// is hereby granted, provided that the above copyright notice and this
// permission notice appear in all copies.
(function (root) {
  'use strict';
  const ICONS = ${JSON.stringify(out, null, 1)};
  // An icon as inline SVG, stroked in the current text colour.
  function icon(name, size, stroke) {
    const i = ICONS[name] || ICONS.check;
    return '<svg class="ico" width="' + size + '" height="' + size + '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="' + (stroke || 1.4) + '" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' + i.svg + '</svg>';
  }
  const api = { ICONS, icon, names: Object.keys(ICONS) };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.SlideIcons = api;
})(typeof self !== 'undefined' ? self : this);
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'shared', 'icons.js'), body);
console.log(`wrote ${ICONS.length} icons`);
